# Generated by Django 2.2 on 2019-12-31 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sns_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respost',
            options={'verbose_name': 'ポスト', 'verbose_name_plural': 'ポスト'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'verbose_name': 'スレッド', 'verbose_name_plural': 'スレッド'},
        ),
        migrations.AddField(
            model_name='respost',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
