# Generated by Django 2.2 on 2020-01-02 15:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sns_app', '0002_auto_20191231_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respost',
            name='posted_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 2, 15, 12, 19, 455573, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_created_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 2, 15, 12, 19, 455573, tzinfo=utc)),
        ),
    ]
