# Generated by Django 2.2 on 2020-01-02 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sns_app', '0003_auto_20200103_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respost',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
